language: java
jdk: oraclejdk8
sudo: required
script:
- "./mvnw clean install -B"
- "./mvnw clean package sonar:sonar"
services:
- docker
env:
  global:
  - secure: M3zN4Znn55nxs6aFhTfliFZLAVO7YolqUCCYM4fcvZLmzVfsisy4kWDXp6KwcW1e8ZDRtw0Mqy918GGkRzG5I/U523byXRhMxO7XyXq13+II4HsFfvOHXQ+uC2miVMZCMuwskrTCnHlHrbUpi8Vz1kPE9WiS7672i9GRtZqqRwcqY3Z2YCewZsQqX+zmzlgByLNdw5hqtXwfmZMXQnULLHkmxlwE9vV5hm8C3NP/FhgJvIZjN5H2uhTYteZTuSFdpBge2tSUO6Zw5zkHxXZfRURNj0TGItcPE+dd3pvFuNaaIjRpCns4PuSMTxmgAP4/COAnuZYuYWBcmdoDMCOrHdbxVzGxEH+4ZPCYLUTngTyjkxYgih8FJ+VbGl1cI13MfVYlkXcTQw2yuEpdEiReMS+TM1s/0YeN3Q9TsqI/dWY+nCN383cIKnSe4agjw9ZCODS70AN2asoTOfKEDvyT1t4suLocmpNsx0HTzLJsyEGcduYinxSpzm2+2mBzHxzrW+ETjoYVR/jh+Qsqy4xupFPXqnE6qpUm61NWTSVkct0GEvAFpRcZy23r6mKIv56KnmHOln3Fz6t2T0m+24XCfR39X1O7VCfZ/wdTFI2fNzhK5W0No2IYy9hWhpvdT+dxoiDvhcFBW/uYUVpP0JeTddLhdSqRkXnlp5BUUBfJbGI=
  - secure: DRZdIT+hQtCOgIfB/UmD0qsNXAHtuw4nLM/3ANyapmw0Dos+o4/C2uGuqarBmAXoz3yz0ggtHabHbgdEoS3tXNMoR9eyBuear6wfOWaGyTIPPphVyF9Ep3s5DMXTFHg3utVXMqxzonAkfzqpdC/FbkvuCReYF1pR2MEDsVcGUdpHGSnTyspnNF8rhYf8DMWMHaahc0jlkxaX8JxrRNELOwvTRTbR7S18MqQkKiLdwSc5llxSN73c1GPNhc5WqwcPAXuQxfyyJZ7nv07oT/UHDsqt5Cymz0Uh5QzsdyUBQLsp+B9cxVJQSVAqwSam3jeoRME1p5HZQQMm0QK8cibTuE3Wpoa9cdWCCeSeZ0N8e53uqxRcWtpnkBhZdopb2a5Nj1kJil3aDdVAX2tAK5GLS03d1y1O1QcK7iXk/0Tp2tjPDi2L+gqf3D7oEB1obnd/00i5p11VLUjna5F1GdljW/RLblHUazTlE3+xbjma2gnFoP1pxJ0/Y+wmp3PlPS9S3tffkSHbqDMngeVbpQTEuog/uW3GEMuDg83inRiz7lVy+rcviwt2Xhd5Qj1WjYuvQv1k/rI0gRZ5ifnTizvGfjR1bXQ6vlsRKBKDK5W8lBCYx/kVewgJaD5SfeS1IN0merJbedL3FNTSmmv5NGgnGOnSaWVmOFooJ7AKn+QrlFA=
  - secure: T0XDPUkmkNO6PLklct5zXFCwfV8mUisa5+m0/AK1iOAALT3ydfFggCvv/wug0qg9jsT5hqBeL2HTrIfMXjx8Zhna0prX4Vv0fIoKKz2j1DyI7Kt5e5fJsxNzYaX0kn9cXO4nQ40x6qBTsOuKGuUysXfeIYe5ps6V5y2N/RUpR3jEum82vtlotDKwiENfyNe5eSI7WozxixzaZAHa7E+g02hbWekjS24LLqm4lBz/ysjBt3CwRAxFD55bf2Mq1xatqdgKLiKjrIMlPQLfh5+Qw4YmM8WNXKjwk35HURh6EFpQN6dJB3tJth4/X65M3D3CvlwVtE7erujijTMfkSMwkCWYNPEonKV5VilvOmclgTb+bkiFAkLuUQV/EsGZXeJkPxm8ENHzouv2CLkuGVjmeduCCxgk25YUPeBQEwBdl29jFtiYlOnfBdlZSZW1U/5M7YcvSTzrueC9J1rsAAWL9fdEzW+dRAKSGr5KXRlp1vsriGb6/uAfb9Kj98BRXEEkmw9bqhwZa8HiNSoOlqnZK5f0Hu8ZEZozasJJ07gMkGboCUAP1McQd2G05s/HWAyDRA2Ov5q22g9uz7KIPCyV6KdfvpMF72wMEWvBQV1wZb/kIdfqNsyAvW5+35A/siTkdkBSy+MrhxXqN4f7VjWhAXl3VsdWlOVY3y+6M43x4zM=
addons:
  sonarcloud:
    organization: mr-cell-github
    token:
      secure: "$SONAR_TOKEN"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=mrcell/spring-demo
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
