language: java
jdk: oraclejdk8
sudo: required
script:
- "./mvnw clean install -B"
- "./mvnw clean package sonar:sonar"
services:
- docker
env:
  global:
  - secure: M3zN4Znn55nxs6aFhTfliFZLAVO7YolqUCCYM4fcvZLmzVfsisy4kWDXp6KwcW1e8ZDRtw0Mqy918GGkRzG5I/U523byXRhMxO7XyXq13+II4HsFfvOHXQ+uC2miVMZCMuwskrTCnHlHrbUpi8Vz1kPE9WiS7672i9GRtZqqRwcqY3Z2YCewZsQqX+zmzlgByLNdw5hqtXwfmZMXQnULLHkmxlwE9vV5hm8C3NP/FhgJvIZjN5H2uhTYteZTuSFdpBge2tSUO6Zw5zkHxXZfRURNj0TGItcPE+dd3pvFuNaaIjRpCns4PuSMTxmgAP4/COAnuZYuYWBcmdoDMCOrHdbxVzGxEH+4ZPCYLUTngTyjkxYgih8FJ+VbGl1cI13MfVYlkXcTQw2yuEpdEiReMS+TM1s/0YeN3Q9TsqI/dWY+nCN383cIKnSe4agjw9ZCODS70AN2asoTOfKEDvyT1t4suLocmpNsx0HTzLJsyEGcduYinxSpzm2+2mBzHxzrW+ETjoYVR/jh+Qsqy4xupFPXqnE6qpUm61NWTSVkct0GEvAFpRcZy23r6mKIv56KnmHOln3Fz6t2T0m+24XCfR39X1O7VCfZ/wdTFI2fNzhK5W0No2IYy9hWhpvdT+dxoiDvhcFBW/uYUVpP0JeTddLhdSqRkXnlp5BUUBfJbGI=
  - secure: DRZdIT+hQtCOgIfB/UmD0qsNXAHtuw4nLM/3ANyapmw0Dos+o4/C2uGuqarBmAXoz3yz0ggtHabHbgdEoS3tXNMoR9eyBuear6wfOWaGyTIPPphVyF9Ep3s5DMXTFHg3utVXMqxzonAkfzqpdC/FbkvuCReYF1pR2MEDsVcGUdpHGSnTyspnNF8rhYf8DMWMHaahc0jlkxaX8JxrRNELOwvTRTbR7S18MqQkKiLdwSc5llxSN73c1GPNhc5WqwcPAXuQxfyyJZ7nv07oT/UHDsqt5Cymz0Uh5QzsdyUBQLsp+B9cxVJQSVAqwSam3jeoRME1p5HZQQMm0QK8cibTuE3Wpoa9cdWCCeSeZ0N8e53uqxRcWtpnkBhZdopb2a5Nj1kJil3aDdVAX2tAK5GLS03d1y1O1QcK7iXk/0Tp2tjPDi2L+gqf3D7oEB1obnd/00i5p11VLUjna5F1GdljW/RLblHUazTlE3+xbjma2gnFoP1pxJ0/Y+wmp3PlPS9S3tffkSHbqDMngeVbpQTEuog/uW3GEMuDg83inRiz7lVy+rcviwt2Xhd5Qj1WjYuvQv1k/rI0gRZ5ifnTizvGfjR1bXQ6vlsRKBKDK5W8lBCYx/kVewgJaD5SfeS1IN0merJbedL3FNTSmmv5NGgnGOnSaWVmOFooJ7AKn+QrlFA=
  - secure: N4j1fopZDu5eWuygcNeH78Ps/O6skx4V6LUmrMOdOHYMSumk82jAhh9cQNPIgII7WF4h8LB0lO29MO4J6H5hzNiiruFbDosAnbwCE9i38ckfP3eoTKz8Y+umAHcaKEeEFrBJods+lyWEG+v0fgKPVBJnTSUc4AmPJHv3YWXbMJjreyy53lMdWx3rU+ga49yl/8xWmGibCh4cS3yvhyfa3HNtBTnAGJwGRtckfctKMYdlG7anFbApBLGdyuRMklJJlmhLfFyWhV9ABVu17LLKLifbDcIKso5jMFFXjvtrdEeNwExnakX9tSqnqznBWK9DxcGTejYU/5HieHuJDG+Bmwtk1GgEYzNBYjvc8kkQKn3IvNrSZDGmxR712UvXHJ00am/7KstTp0Hr9VbzntcNObS4qtJ/IqPwEcEcgzHyN6GLIeSJHEwrVN0yboOLgwuAXXWjNrq5mm6tw74zn5H/3DqebYXOQ+X1E/NvPQdn2UP66gzfb3lNSPididtEVxw/mwHmE95I7FeRxpjXdktKhbgtsXNt0Lqufp0ovqqYqqZ5DRnfocwVboXAFvllEiTTdDLqSCL/EHZLRbIce8E4blJ/jHyRve4SD6QikHP5Lro/BFDs9VtUKFN8wojWvs0OloDT+H0pnfPntB77q/izrQzDMLbL91oWqh3mY0A8Tjk=
  - secure: Ir7Jql9R3Lv9PW92kv+8MwQXwCxKlIUMpg1Wq/8ldv4Hs6fcvOyQA6+0g0h7thk2ObwWFIXXUYLfyyn/tc131A38CF8ie9S6c9rKaTc6KpOldAltO47uY+UvYM4IfIZm54wOo4qNbMd+0ZQ3afdUxCy16rgoWrHFv93V9/mi+1RjnzK4AzNrb3Hf3m18O82XdyuboY08sVsf+EKJVjDy5cx6DoMohMiHysl9oeJDRGG9ivReKKtdhk4CCM3vW62sVY7akxaRW8mwN1c0YOfplq5gNAdlRftGUs4WeJCid2qauFUtSrcgKiBvHM84Jnx2pwtrEgHr/5PukIfrycLpT2izecO4yfxgAXuyJP6YfSqCWaB2X5hTjNPZ0MGh66WknDLjQTPZo5MbgIG40CB3zii2XMOC+dIKsejETn/jc8wgGbUt45dXM4EfQ1zLnfjSjb68jO/3NnAQTc1JURikJtnFTtjdFPpeoCoMwXxAeFFxrfL0htQPGQ/O4JJJRVbtMicaq+VCVHU1Dkob/QtN1dGbcscEeBK6SGB6Sigyu1d08zXuVQmozOQkIvBci/7XbSuXl6YIBwEEDL0EBEuA50tAFx9g0iVV0c+qKUJAhKh/ei0ZBW6VlZY9kNWkW9v8YntlQReebmnumQW/bAH9OYNV1WcBg9b2NCPnGimYxV0=
addons:
  sonarcloud:
    organization: mr-cell-github
    token:
      secure: "$SONAR_TOKEN"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=mrcell/spring-demo
- docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
- docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TRAVIS_TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mrcell-spring-demo